title: Yzj Tracking Some Deadlines
description: Countdowns to some deadlines
author: Zijian Yu

domain: "yzj2019.github.io"
baseurl: "/ai-deadlines"

# twitter_hashtag: machinelearning
github_username: yzj2019
github_repo: ai-deadlines

markdown: kramdown
ga_id:

include: ['_pages']
